/*
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference
 *
 * algorithms
 * Easy (50.53%)
 * Total Accepted:    76.2K
 * Total Submissions: 150.8K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 * 
 */
/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
const findTheDifference = (s, t) => {
  let hash = {}
  for (let v of [...t]) {
    hash[v] ? hash[v]++ : (hash[v] = 1)
  }
  for (let v of [...s]) {
    hash[v]--
  }
  for (let key in hash) {
    if (hash[key] === 1) return key
  }
}
